import React,{useEffect,useMemo,useRef,useState} from 'react';
import {BrowserMultiFormatReader} from '@zxing/browser';
import {supabase} from './lib/supabase';

const lines=['Line 1','Line 2','Line 3'];
const demoRows=[['P-6501','GM0104000'],['P-6502','GM0104002'],['P-6503','GM0104004'],['P-6504','GM0104006']];
function parseText(text){const rows=[]; for(const line of text.split(/\r?\n/)){const m=line.match(/(P-\d+)\s+(GM\d+)/i); if(m) rows.push({label_number:m[1],serial_number:m[2]});} return rows;}
function csvRows(text){const out=[]; for(const line of text.split(/\r?\n/).slice(1)){const c=line.split(',').map(x=>x.trim()); if(c[0]&&c[1]) out.push({label_number:c[0],serial_number:c[1]});} return out;}
export default function App(){
 const [view,setView]=useState('dashboard'); const [plans,setPlans]=useState([]); const [selectedPlan,setSelectedPlan]=useState(null); const [rows,setRows]=useState([]); const [message,setMessage]=useState('');
 const [form,setForm]=useState({production_date:new Date().toISOString().slice(0,10),product_name:'LifeLong OTG',model:'RCAD60',production_line:'Line 2',planned_qty:500});
 const [operator,setOperator]=useState('Operator'); const [camera,setCamera]=useState(false); const videoRef=useRef(null); const readerRef=useRef(null);
 const load=async()=>{const {data}=await supabase.from('production_plans').select('*').order('production_date',{ascending:false}).limit(50); if(data) setPlans(data)};
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>plans.reduce((a,p)=>{a.target+=p.planned_qty||0;return a},{target:0}),[plans]);
 const importFile=async e=>{const f=e.target.files?.[0]; if(!f)return; const text=await f.text(); let parsed=f.name.toLowerCase().endsWith('.csv')?csvRows(text):parseText(text); if(!parsed.length && f.name.toLowerCase().endsWith('.pdf')) setMessage('PDF text could not be extracted in this browser build. Use CSV/TXT export for this batch.'); else {setRows(parsed);setMessage(`${parsed.length} serials loaded from ${f.name}`)}};
 const createPlan=async()=>{setMessage('Creating plan...'); const qty=Number(form.planned_qty); if(!form.product_name||!form.model||!qty)return setMessage('Enter product, model and quantity.'); const {data,error}=await supabase.from('production_plans').insert({...form,planned_qty:qty,status:'active'}).select().single(); if(error)return setMessage(error.message); const source=rows.length?rows:demoRows; const chosen=source.slice(0,qty); const payload=chosen.map((r,i)=>({...r,plan_id:data.id,sequence_no:i+1})); if(payload.length){const {error:e2}=await supabase.from('plan_serials').insert(payload); if(e2){setMessage(e2.message);return}} await load(); setSelectedPlan(data); setMessage(`Plan created with ${payload.length} serials.`); setView('plans');};
 const scan=async value=>{if(!selectedPlan||!value)return; const clean=value.trim(); const {data}=await supabase.from('plan_serials').select('*').eq('plan_id',selectedPlan.id).eq('serial_number',clean).maybeSingle(); if(!data){setMessage(`NOT PLANNED: ${clean}`);return} if(data.status==='scanned'){setMessage(`DUPLICATE: ${clean}`);return} const {error}=await supabase.from('plan_serials').update({status:'scanned',scanned_at:new Date().toISOString(),scanned_by:operator}).eq('id',data.id); setMessage(error?error.message:`✓ Scanned ${clean}`)};
 const startCamera=async()=>{setCamera(true); const r=new BrowserMultiFormatReader(); readerRef.current=r; try{await r.decodeFromVideoDevice(undefined,videoRef.current,(result)=>{if(result){scan(result.getText());}})}catch(e){setMessage('Camera could not start. Check browser camera permission.')}};
 const stopCamera=()=>{try{readerRef.current?.reset()}catch{} setCamera(false)};
 return <div className='app'><header><div><span className='eyebrow'>PRODUCTION CONTROL</span><h1>Pro Scan</h1></div><div className='top-actions'><span className='live'>● LIVE</span><button onClick={()=>setView('dashboard')}>Dashboard</button><button onClick={()=>setView('planner')}>Production Planner</button><button onClick={()=>setView('operator')}>Operator</button></div></header>
 {view==='dashboard'&&<main><section className='hero'><div><span className='eyebrow'>CONTROL CENTRE</span><h2>Today's production</h2><p>Create the plan first, then let operators scan only the serials allocated to that plan.</p></div><button className='primary' onClick={()=>setView('planner')}>+ Create Production Plan</button></section><div className='cards'><div><b>{plans.length}</b><span>Active / recent plans</span></div><div><b>{stats.target}</b><span>Total planned units</span></div><div><b>{plans.filter(p=>p.status==='active').length}</b><span>Active today</span></div></div><section className='panel'><div className='panel-head'><h3>Production plans</h3><button onClick={load}>Refresh</button></div><table><thead><tr><th>Date</th><th>Product</th><th>Model</th><th>Line</th><th>Qty</th><th>Status</th></tr></thead><tbody>{plans.map(p=><tr key={p.id} onClick={()=>{setSelectedPlan(p);setView('operator')}}><td>{p.production_date}</td><td>{p.product_name}</td><td>{p.model}</td><td>{p.production_line}</td><td>{p.planned_qty}</td><td><span className='badge'>{p.status}</span></td></tr>)}</tbody></table>{!plans.length&&<div className='empty'>No production plan yet.</div>}</section></main>}
 {view==='planner'&&<main><section className='panel'><div className='panel-head'><div><span className='eyebrow'>ADMIN / PLANNER</span><h2>Create daily production plan</h2></div><button onClick={()=>setView('dashboard')}>Back</button></div><div className='grid'><label>Production date<input type='date' value={form.production_date} onChange={e=>setForm({...form,production_date:e.target.value})}/></label><label>Product<input value={form.product_name} onChange={e=>setForm({...form,product_name:e.target.value})}/></label><label>Model<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label>Production line<select value={form.production_line} onChange={e=>setForm({...form,production_line:e.target.value})}>{lines.map(x=><option key={x}>{x}</option>)}</select></label><label>Planned quantity<input type='number' min='1' value={form.planned_qty} onChange={e=>setForm({...form,planned_qty:e.target.value})}/></label></div><div className='upload'><h3>Serial number allocation</h3><p>Upload CSV/TXT exported from your supplier file. CSV format: <b>Label,Serial</b>. Your RCAD60 batch follows the same two-column relationship, e.g. P-6501 → GM0104000.</p><input type='file' accept='.csv,.txt,.pdf' onChange={importFile}/><div className='range'>{rows.length?<><b>{rows.length}</b> serials loaded</>:<>No serial file loaded. A demo set is used if you create a test plan.</>}</div></div><div className='actions'><button className='primary' onClick={createPlan}>Create Production Plan</button></div>{message&&<div className='notice'>{message}</div>}</section></main>}
 {view==='plans'&&<main><section className='panel'><div className='panel-head'><h2>Plan created</h2><button onClick={()=>setView('dashboard')}>Dashboard</button></div><div className='success'>Production plan is active and ready for scanning.</div></section></main>}
 {view==='operator'&&<main><section className='operator-card'><div className='operator-top'><div><span className='eyebrow'>OPERATOR SCAN</span><h2>{selectedPlan?.product_name||'Select a plan'}</h2><p>{selectedPlan?.model||''} · {selectedPlan?.production_line||''}</p></div><label>Operator<input value={operator} onChange={e=>setOperator(e.target.value)}/></label></div><div className='scanner'>{camera?<video ref={videoRef} autoPlay muted playsInline/>:<div className='camera-placeholder'>Camera scanner ready</div>}</div><div className='scan-actions'>{camera?<button className='primary' onClick={stopCamera}>Stop Camera</button>:<button className='primary' onClick={startCamera} disabled={!selectedPlan}>Start Camera Scan</button>}<input placeholder='Or enter serial manually' onKeyDown={e=>{if(e.key==='Enter'){scan(e.currentTarget.value);e.currentTarget.value=''}}}/></div><div className='status'>{message||'Ready to scan'}</div></section></main>}
 </div>
}
