-- Pro Scan custom database-backed authentication.
-- Password hashes use bcrypt generated by the app-auth Edge Function.
-- User-specific one-time setup hashes are provisioned separately.

alter table public.app_users
  add column if not exists password_hash text,
  add column if not exists setup_token_hash text,
  add column if not exists is_active boolean not null default true;

alter table public.app_users drop constraint if exists app_users_role_check;
update public.app_users
set email = lower(btrim(email)),
    role = case role when 'admin' then 'super_admin' when 'supervisor' then 'planner' else role end,
    updated_at = now()
where email is distinct from lower(btrim(email))
   or role in ('admin','supervisor');
alter table public.app_users
  add constraint app_users_role_check check (role = any (array['super_admin','planner','operator']));

create table if not exists public.app_auth_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.app_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);
create index if not exists idx_app_auth_sessions_user_expiry
  on public.app_auth_sessions(user_id, expires_at desc);

create table if not exists public.app_login_attempts (
  id bigint generated always as identity primary key,
  email text not null,
  ip_hash text not null,
  succeeded boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_app_login_attempts_rate
  on public.app_login_attempts(email, ip_hash, succeeded, created_at desc);

alter table public.app_auth_sessions enable row level security;
alter table public.app_login_attempts enable row level security;
alter table public.app_users enable row level security;
revoke all on public.app_auth_sessions from anon, authenticated;
revoke all on public.app_login_attempts from anon, authenticated;
revoke all on public.app_users from anon, authenticated;
grant select, insert, update, delete on public.app_auth_sessions to service_role;
grant select, insert, update, delete on public.app_login_attempts to service_role;
grant select, insert, update, delete on public.app_users to service_role;
grant usage, select on sequence public.app_login_attempts_id_seq to service_role;

grant select, insert, update on public.production_plans to anon, authenticated;
grant select, insert, update on public.plan_serials to anon, authenticated;
grant select, insert on public.scan_events to anon, authenticated;
grant select, insert, update on public.serial_numbers to anon, authenticated;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated;

create or replace function private.custom_app_role()
returns text
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
declare
  session_token text;
  resolved_role text;
  headers jsonb;
begin
  headers := coalesce(current_setting('request.headers', true), '{}')::jsonb;
  session_token := nullif(headers ->> 'x-app-session', '');
  if session_token is null then return ''; end if;

  select u.role into resolved_role
  from public.app_auth_sessions s
  join public.app_users u on u.id = s.user_id
  where s.token_hash = encode(extensions.digest(session_token, 'sha256'), 'hex')
    and s.expires_at > now()
    and s.revoked_at is null
    and u.is_active = true
  limit 1;

  return coalesce(resolved_role, '');
exception when others then
  return '';
end;
$$;
revoke all on function private.custom_app_role() from public;
grant execute on function private.custom_app_role() to anon, authenticated;

drop policy if exists "app users read own role" on public.app_users;
drop policy if exists "app users admin manage" on public.app_users;
drop policy if exists "deny client app users access" on public.app_users;
create policy "deny client app users access" on public.app_users
for all to anon, authenticated using (false) with check (false);

drop policy if exists "deny client app sessions access" on public.app_auth_sessions;
create policy "deny client app sessions access" on public.app_auth_sessions
for all to anon, authenticated using (false) with check (false);

drop policy if exists "deny client login attempts access" on public.app_login_attempts;
create policy "deny client login attempts access" on public.app_login_attempts
for all to anon, authenticated using (false) with check (false);

drop policy if exists "role read production plans" on public.production_plans;
drop policy if exists "management insert production plans" on public.production_plans;
drop policy if exists "management update production plans" on public.production_plans;
drop policy if exists "role read plan serials" on public.plan_serials;
drop policy if exists "management insert plan serials" on public.plan_serials;
drop policy if exists "operator update plan serials" on public.plan_serials;
drop policy if exists "role read scan events" on public.scan_events;
drop policy if exists "role insert scan events" on public.scan_events;
drop policy if exists "management read serial numbers" on public.serial_numbers;
drop policy if exists "management insert serial numbers" on public.serial_numbers;
drop policy if exists "management update serial numbers" on public.serial_numbers;

drop policy if exists "custom role read production plans" on public.production_plans;
drop policy if exists "custom role read production plans" on public.production_plans;
create policy "custom role read production plans" on public.production_plans
for select to anon, authenticated
using (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom management insert production plans" on public.production_plans;
drop policy if exists "custom management insert production plans" on public.production_plans;
create policy "custom management insert production plans" on public.production_plans
for insert to anon, authenticated
with check (private.custom_app_role() in ('planner','super_admin'));

drop policy if exists "custom management update production plans" on public.production_plans;
drop policy if exists "custom management update production plans" on public.production_plans;
create policy "custom management update production plans" on public.production_plans
for update to anon, authenticated
using (private.custom_app_role() in ('operator','planner','super_admin'))
with check (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom role read plan serials" on public.plan_serials;
drop policy if exists "custom role read plan serials" on public.plan_serials;
create policy "custom role read plan serials" on public.plan_serials
for select to anon, authenticated
using (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom management insert plan serials" on public.plan_serials;
drop policy if exists "custom management insert plan serials" on public.plan_serials;
create policy "custom management insert plan serials" on public.plan_serials
for insert to anon, authenticated
with check (private.custom_app_role() in ('planner','super_admin'));

drop policy if exists "custom operator update plan serials" on public.plan_serials;
drop policy if exists "custom operator update plan serials" on public.plan_serials;
create policy "custom operator update plan serials" on public.plan_serials
for update to anon, authenticated
using (private.custom_app_role() in ('operator','planner','super_admin'))
with check (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom role read scan events" on public.scan_events;
drop policy if exists "custom role read scan events" on public.scan_events;
create policy "custom role read scan events" on public.scan_events
for select to anon, authenticated
using (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom role insert scan events" on public.scan_events;
drop policy if exists "custom role insert scan events" on public.scan_events;
create policy "custom role insert scan events" on public.scan_events
for insert to anon, authenticated
with check (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom management read serial numbers" on public.serial_numbers;
drop policy if exists "custom management read serial numbers" on public.serial_numbers;
create policy "custom management read serial numbers" on public.serial_numbers
for select to anon, authenticated
using (private.custom_app_role() in ('planner','super_admin'));

drop policy if exists "custom management insert serial numbers" on public.serial_numbers;
drop policy if exists "custom management insert serial numbers" on public.serial_numbers;
create policy "custom management insert serial numbers" on public.serial_numbers
for insert to anon, authenticated
with check (private.custom_app_role() in ('planner','super_admin'));

drop policy if exists "custom management update serial numbers" on public.serial_numbers;
drop policy if exists "custom management update serial numbers" on public.serial_numbers;
create policy "custom management update serial numbers" on public.serial_numbers
for update to anon, authenticated
using (private.custom_app_role() in ('planner','super_admin'))
with check (private.custom_app_role() in ('planner','super_admin'));

create or replace function public.protect_operator_plan_update()
returns trigger
language plpgsql
security invoker
set search_path = public, private
as $$
declare caller_role text;
begin
  caller_role := coalesce(private.custom_app_role(), '');
  if caller_role = 'operator' then
    if new.production_date is distinct from old.production_date
       or new.product_name is distinct from old.product_name
       or new.brand is distinct from old.brand
       or new.model is distinct from old.model
       or new.production_line is distinct from old.production_line
       or new.planned_qty is distinct from old.planned_qty
       or new.hourly_targets is distinct from old.hourly_targets then
      raise exception 'Operators may only change production plan status';
    end if;
    if new.status not in ('draft','active','completed','cancelled') then
      raise exception 'Invalid production plan status';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists protect_operator_plan_update on public.production_plans;
create trigger protect_operator_plan_update
before update on public.production_plans
for each row execute function public.protect_operator_plan_update();

drop function if exists public.current_app_role();
drop function if exists public.custom_app_role();

create index if not exists idx_plan_serials_serial_number_id
  on public.plan_serials(serial_number_id);
create index if not exists idx_scan_events_serial_number_id
  on public.scan_events(serial_number_id);

-- Atomic Draft plan update keeps its header, hourly schedule, and serial list consistent.
create or replace function public.update_draft_production_plan(p_plan_id uuid,p_production_date date,p_brand text,p_product_name text,p_model text,p_production_line text,p_planned_qty integer,p_hourly_targets jsonb,p_serial_pairs jsonb)
returns public.production_plans language plpgsql security definer set search_path=public,private,extensions as $$
declare existing_plan public.production_plans%rowtype; updated_plan public.production_plans%rowtype; pair_count integer; hourly_total integer;
begin
 if coalesce(private.custom_app_role(),'') not in ('planner','super_admin') then raise exception 'Only Planner or Super Admin can edit production plans'; end if;
 select * into existing_plan from public.production_plans where id=p_plan_id for update;
 if not found then raise exception 'Production plan was not found'; end if;
 if existing_plan.status<>'draft' then raise exception 'Only Draft production plans can be edited'; end if;
 if exists(select 1 from public.plan_serials where plan_id=p_plan_id and status='scanned') then raise exception 'Draft plan has scanned serials'; end if;
 if p_production_date is null or nullif(btrim(coalesce(p_product_name,'')),'') is null or nullif(btrim(coalesce(p_model,'')),'') is null or nullif(btrim(coalesce(p_production_line,'')),'') is null then raise exception 'Enter a production date, product, model, and line'; end if;
 if p_planned_qty is null or p_planned_qty<1 then raise exception 'Planned quantity must be at least one'; end if;
 if jsonb_typeof(p_serial_pairs)<>'array' or jsonb_array_length(p_serial_pairs)<>p_planned_qty then raise exception 'Planned quantity must match the selected serial pairs'; end if;
 pair_count:=jsonb_array_length(p_serial_pairs);
 if exists(select 1 from jsonb_to_recordset(p_serial_pairs) as p(label_number text,serial_number text) where nullif(btrim(coalesce(p.label_number,'')),'') is null or nullif(btrim(coalesce(p.serial_number,'')),'') is null) then raise exception 'Each allocation needs a label and serial number'; end if;
 if (select count(distinct label_number) from jsonb_to_recordset(p_serial_pairs) as p(label_number text,serial_number text))<>pair_count or (select count(distinct serial_number) from jsonb_to_recordset(p_serial_pairs) as p(label_number text,serial_number text))<>pair_count then raise exception 'Serial and label values must be unique'; end if;
 if jsonb_typeof(p_hourly_targets)<>'array' or jsonb_array_length(p_hourly_targets)=0 then raise exception 'At least one hourly target is required'; end if;
 if exists(select 1 from jsonb_array_elements(p_hourly_targets) as t(value) where coalesce(t.value->>'hour','') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' or coalesce(t.value->>'planned_qty','') !~ '^[0-9]+$') then raise exception 'Hourly targets contain invalid values'; end if;
 if (select count(*) from jsonb_array_elements(p_hourly_targets))<>(select count(distinct value->>'hour') from jsonb_array_elements(p_hourly_targets)) then raise exception 'Hourly target times must be unique'; end if;
 select coalesce(sum((value->>'planned_qty')::integer),0) into hourly_total from jsonb_array_elements(p_hourly_targets);
 if hourly_total<>p_planned_qty then raise exception 'Hourly targets must total the planned quantity'; end if;
 if exists(select 1 from public.plan_serials existing join jsonb_to_recordset(p_serial_pairs) as incoming(label_number text,serial_number text) on existing.serial_number=incoming.serial_number or existing.label_number=incoming.label_number where existing.plan_id<>p_plan_id) then raise exception 'Serial or label is allocated to another plan'; end if;
 if exists(select 1 from public.serial_numbers registry join jsonb_to_recordset(p_serial_pairs) as incoming(label_number text,serial_number text) on registry.serial_number=incoming.serial_number where not exists(select 1 from public.plan_serials own where own.plan_id=p_plan_id and own.serial_number=registry.serial_number)) then raise exception 'Serial exists in serial registry'; end if;
 update public.production_plans set production_date=p_production_date,brand=coalesce(nullif(btrim(p_brand),''),'Unspecified'),product_name=btrim(p_product_name),model=btrim(p_model),production_line=btrim(p_production_line),planned_qty=p_planned_qty,hourly_targets=p_hourly_targets where id=p_plan_id and status='draft' returning * into updated_plan;
 if not found then raise exception 'Plan is no longer Draft'; end if;
 delete from public.plan_serials where plan_id=p_plan_id;
 insert into public.plan_serials(plan_id,label_number,serial_number,sequence_no,status) select p_plan_id,btrim(p.label_number),btrim(p.serial_number),p.ordinality::integer,'pending' from jsonb_to_recordset(p_serial_pairs) with ordinality as p(label_number text,serial_number text,ordinality bigint) order by p.ordinality;
 return updated_plan;
end; $$;
revoke all on function public.update_draft_production_plan(uuid,date,text,text,text,text,integer,jsonb,jsonb) from public;
grant execute on function public.update_draft_production_plan(uuid,date,text,text,text,text,integer,jsonb,jsonb) to anon,authenticated;
