-- Pro Scan custom database-backed authentication.
-- Password hashes use bcrypt generated by the app-auth Edge Function.
-- User-specific one-time setup hashes are provisioned separately.

alter table public.app_users
  add column if not exists password_hash text,
  add column if not exists setup_token_hash text,
  add column if not exists is_active boolean not null default true;

alter table public.app_users drop constraint if exists app_users_role_check;
update public.app_users
set email = lower(btrim(email)),
    role = case role when 'admin' then 'super_admin' when 'supervisor' then 'planner' else role end,
    updated_at = now()
where email is distinct from lower(btrim(email))
   or role in ('admin','supervisor');
alter table public.app_users
  add constraint app_users_role_check check (role = any (array['super_admin','planner','operator']));

create table if not exists public.app_auth_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.app_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);
create index if not exists idx_app_auth_sessions_user_expiry
  on public.app_auth_sessions(user_id, expires_at desc);

create table if not exists public.app_login_attempts (
  id bigint generated always as identity primary key,
  email text not null,
  ip_hash text not null,
  succeeded boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_app_login_attempts_rate
  on public.app_login_attempts(email, ip_hash, succeeded, created_at desc);

alter table public.app_auth_sessions enable row level security;
alter table public.app_login_attempts enable row level security;
alter table public.app_users enable row level security;
revoke all on public.app_auth_sessions from anon, authenticated;
revoke all on public.app_login_attempts from anon, authenticated;
revoke all on public.app_users from anon, authenticated;
grant select, insert, update, delete on public.app_auth_sessions to service_role;
grant select, insert, update, delete on public.app_login_attempts to service_role;
grant select, insert, update, delete on public.app_users to service_role;
grant usage, select on sequence public.app_login_attempts_id_seq to service_role;

grant select, insert, update on public.production_plans to anon, authenticated;
grant select, insert, update on public.plan_serials to anon, authenticated;
grant select, insert on public.scan_events to anon, authenticated;
grant select, insert, update on public.serial_numbers to anon, authenticated;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated;

create or replace function private.custom_app_role()
returns text
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
declare
  session_token text;
  resolved_role text;
  headers jsonb;
begin
  headers := coalesce(current_setting('request.headers', true), '{}')::jsonb;
  session_token := nullif(headers ->> 'x-app-session', '');
  if session_token is null then return ''; end if;

  select u.role into resolved_role
  from public.app_auth_sessions s
  join public.app_users u on u.id = s.user_id
  where s.token_hash = encode(extensions.digest(session_token, 'sha256'), 'hex')
    and s.expires_at > now()
    and s.revoked_at is null
    and u.is_active = true
  limit 1;

  return coalesce(resolved_role, '');
exception when others then
  return '';
end;
$$;
revoke all on function private.custom_app_role() from public;
grant execute on function private.custom_app_role() to anon, authenticated;

drop policy if exists "app users read own role" on public.app_users;
drop policy if exists "app users admin manage" on public.app_users;
drop policy if exists "deny client app users access" on public.app_users;
create policy "deny client app users access" on public.app_users
for all to anon, authenticated using (false) with check (false);

drop policy if exists "deny client app sessions access" on public.app_auth_sessions;
create policy "deny client app sessions access" on public.app_auth_sessions
for all to anon, authenticated using (false) with check (false);

drop policy if exists "deny client login attempts access" on public.app_login_attempts;
create policy "deny client login attempts access" on public.app_login_attempts
for all to anon, authenticated using (false) with check (false);

drop policy if exists "role read production plans" on public.production_plans;
drop policy if exists "management insert production plans" on public.production_plans;
drop policy if exists "management update production plans" on public.production_plans;
drop policy if exists "role read plan serials" on public.plan_serials;
drop policy if exists "management insert plan serials" on public.plan_serials;
drop policy if exists "operator update plan serials" on public.plan_serials;
drop policy if exists "role read scan events" on public.scan_events;
drop policy if exists "role insert scan events" on public.scan_events;
drop policy if exists "management read serial numbers" on public.serial_numbers;
drop policy if exists "management insert serial numbers" on public.serial_numbers;
drop policy if exists "management update serial numbers" on public.serial_numbers;

drop policy if exists "custom role read production plans" on public.production_plans;
drop policy if exists "custom role read production plans" on public.production_plans;
create policy "custom role read production plans" on public.production_plans
for select to anon, authenticated
using (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom management insert production plans" on public.production_plans;
drop policy if exists "custom management insert production plans" on public.production_plans;
create policy "custom management insert production plans" on public.production_plans
for insert to anon, authenticated
with check (private.custom_app_role() in ('planner','super_admin'));

drop policy if exists "custom management update production plans" on public.production_plans;
drop policy if exists "custom management update production plans" on public.production_plans;
create policy "custom management update production plans" on public.production_plans
for update to anon, authenticated
using (private.custom_app_role() in ('operator','planner','super_admin'))
with check (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom role read plan serials" on public.plan_serials;
drop policy if exists "custom role read plan serials" on public.plan_serials;
create policy "custom role read plan serials" on public.plan_serials
for select to anon, authenticated
using (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom management insert plan serials" on public.plan_serials;
drop policy if exists "custom management insert plan serials" on public.plan_serials;
create policy "custom management insert plan serials" on public.plan_serials
for insert to anon, authenticated
with check (private.custom_app_role() in ('planner','super_admin'));

drop policy if exists "custom operator update plan serials" on public.plan_serials;
drop policy if exists "custom operator update plan serials" on public.plan_serials;
create policy "custom operator update plan serials" on public.plan_serials
for update to anon, authenticated
using (private.custom_app_role() in ('operator','planner','super_admin'))
with check (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom role read scan events" on public.scan_events;
drop policy if exists "custom role read scan events" on public.scan_events;
create policy "custom role read scan events" on public.scan_events
for select to anon, authenticated
using (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom role insert scan events" on public.scan_events;
drop policy if exists "custom role insert scan events" on public.scan_events;
create policy "custom role insert scan events" on public.scan_events
for insert to anon, authenticated
with check (private.custom_app_role() in ('operator','planner','super_admin'));

drop policy if exists "custom management read serial numbers" on public.serial_numbers;
drop policy if exists "custom management read serial numbers" on public.serial_numbers;
create policy "custom management read serial numbers" on public.serial_numbers
for select to anon, authenticated
using (private.custom_app_role() in ('planner','super_admin'));

drop policy if exists "custom management insert serial numbers" on public.serial_numbers;
drop policy if exists "custom management insert serial numbers" on public.serial_numbers;
create policy "custom management insert serial numbers" on public.serial_numbers
for insert to anon, authenticated
with check (private.custom_app_role() in ('planner','super_admin'));

drop policy if exists "custom management update serial numbers" on public.serial_numbers;
drop policy if exists "custom management update serial numbers" on public.serial_numbers;
create policy "custom management update serial numbers" on public.serial_numbers
for update to anon, authenticated
using (private.custom_app_role() in ('planner','super_admin'))
with check (private.custom_app_role() in ('planner','super_admin'));

create or replace function public.protect_operator_plan_update()
returns trigger
language plpgsql
security invoker
set search_path = public, private
as $$
declare caller_role text;
begin
  caller_role := coalesce(private.custom_app_role(), '');
  if caller_role = 'operator' then
    if new.production_date is distinct from old.production_date
       or new.product_name is distinct from old.product_name
       or new.brand is distinct from old.brand
       or new.model is distinct from old.model
       or new.production_line is distinct from old.production_line
       or new.planned_qty is distinct from old.planned_qty
       or new.hourly_targets is distinct from old.hourly_targets then
      raise exception 'Operators may only change production plan status';
    end if;
    if new.status not in ('draft','active','completed','cancelled') then
      raise exception 'Invalid production plan status';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists protect_operator_plan_update on public.production_plans;
create trigger protect_operator_plan_update
before update on public.production_plans
for each row execute function public.protect_operator_plan_update();

drop function if exists public.current_app_role();
drop function if exists public.custom_app_role();

create index if not exists idx_plan_serials_serial_number_id
  on public.plan_serials(serial_number_id);
create index if not exists idx_scan_events_serial_number_id
  on public.scan_events(serial_number_id);
