-- Pro Scan custom database-backed authentication.
-- Password hashes are bcrypt hashes generated by the app-auth Edge Function.
-- Account-specific one-time setup hashes are provisioned separately.

alter table public.app_users
  add column if not exists password_hash text,
  add column if not exists setup_token_hash text,
  add column if not exists is_active boolean not null default true;

create table if not exists public.app_auth_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.app_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);
create index if not exists idx_app_auth_sessions_user_expiry
  on public.app_auth_sessions(user_id, expires_at desc);

create table if not exists public.app_login_attempts (
  id bigint generated always as identity primary key,
  email text not null,
  ip_hash text not null,
  succeeded boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_app_login_attempts_rate
  on public.app_login_attempts(email, ip_hash, succeeded, created_at desc);

alter table public.app_auth_sessions enable row level security;
alter table public.app_login_attempts enable row level security;
revoke all on public.app_auth_sessions from anon, authenticated;
revoke all on public.app_login_attempts from anon, authenticated;
grant select, insert, update, delete on public.app_auth_sessions to service_role;
grant select, insert, update, delete on public.app_login_attempts to service_role;
grant select, update on public.app_users to service_role;
revoke all on public.app_users from anon;
grant select, insert, update on public.production_plans to anon, authenticated;
grant select, insert, update on public.plan_serials to anon, authenticated;
grant select, insert on public.scan_events to anon, authenticated;
grant select, insert, update on public.serial_numbers to anon, authenticated;

create or replace function public.custom_app_role()
returns text language plpgsql stable security definer
set search_path = public, extensions
as $$
declare session_token text; resolved_role text; headers jsonb;
begin
  headers := coalesce(current_setting('request.headers', true), '{}')::jsonb;
  session_token := nullif(headers ->> 'x-app-session', '');
  if session_token is null then return ''; end if;
  select u.role into resolved_role
  from public.app_auth_sessions s join public.app_users u on u.id = s.user_id
  where s.token_hash = encode(extensions.digest(session_token, 'sha256'), 'hex')
    and s.expires_at > now() and s.revoked_at is null and u.is_active = true
  limit 1;
  return coalesce(resolved_role, '');
exception when others then return '';
end;
$$;
grant execute on function public.custom_app_role() to anon, authenticated;

create policy "custom role read production plans" on public.production_plans
for select to anon, authenticated using (public.custom_app_role() in ('operator','supervisor','admin'));
create policy "custom management insert production plans" on public.production_plans
for insert to anon, authenticated with check (public.custom_app_role() in ('supervisor','admin'));
create policy "custom management update production plans" on public.production_plans
for update to anon, authenticated using (public.custom_app_role() in ('operator','supervisor','admin'))
with check (public.custom_app_role() in ('operator','supervisor','admin'));

create policy "custom role read plan serials" on public.plan_serials
for select to anon, authenticated using (public.custom_app_role() in ('operator','supervisor','admin'));
create policy "custom management insert plan serials" on public.plan_serials
for insert to anon, authenticated with check (public.custom_app_role() in ('supervisor','admin'));
create policy "custom operator update plan serials" on public.plan_serials
for update to anon, authenticated using (public.custom_app_role() in ('operator','supervisor','admin'))
with check (public.custom_app_role() in ('operator','supervisor','admin'));

create policy "custom role read scan events" on public.scan_events
for select to anon, authenticated using (public.custom_app_role() in ('operator','supervisor','admin'));
create policy "custom role insert scan events" on public.scan_events
for insert to anon, authenticated with check (public.custom_app_role() in ('operator','supervisor','admin'));

create policy "custom management read serial numbers" on public.serial_numbers
for select to anon, authenticated using (public.custom_app_role() in ('supervisor','admin'));
create policy "custom management insert serial numbers" on public.serial_numbers
for insert to anon, authenticated with check (public.custom_app_role() in ('supervisor','admin'));
create policy "custom management update serial numbers" on public.serial_numbers
for update to anon, authenticated using (public.custom_app_role() in ('supervisor','admin'))
with check (public.custom_app_role() in ('supervisor','admin'));
